    jobs:
      build:
        runs-on: ubuntu-latest
        steps:
          - name: Use Node.js
            uses: actions/setup-node@v4
            with:
              node-version: '20'
          - name: Run script with secret
            env:
              MY_SECRET_VARIABLE: ${{ secrets.JS_INJECTION_FLAG }}
            run: |
              node js/injection/flag.html
